<?xml version="1.0" encoding="utf-8"?>
<Application>
  <ModelsRepository>
    <Models/>
  </ModelsRepository>
  <DataSourceRepository/>
  <Header>
    <Version val="12050"/>
    <APPLICATION val="Y"/>
    <WithIsn val="N"/>
    <Exe/>
    <_InternalTask/>
    <IsRoot/>
    <InIndex/>
    <WITH_MODELS/>
    <MAIN_PRG_VARS val="0"/>
    <MAIN_PRG_DSPS val="1"/>
    <Arguments END="2" START="2"/>
  </Header>
  <ProgramsRepository>
    <Programs>
      <Task>
        <Header Description="map_1_5_57">
          <Public val="map_1_5_57"/>
          <ExecutionRight/>
          <Resident val="N"/>
          <SQL val="N"/>
          <ReturnValue>
            <ReturnValueAttr/>
            <ParametersAttributes/>
          </ReturnValue>
          <SqlWhereExist val="N"/>
          <TaskType val="B"/>
          <External val="Y"/>
          <LastModified _date="736327" _time="67871" date="29//12//2016" time="18:51:11.1714800"/>
        </Header>
        <ReturnValueExpression/>
        <Resource>
          <Columns>
            <Column id="1" name="1_Source_DataBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="2" name="3_Destination_DataBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="3" name="3_Destination_XMLIoPtrDll">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_NUMERIC"/>
                <StoredAs/>
                <Size/>
                <_Dec/>
                <_Whole val="3"/>
                <_Negative/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="4" name="3_Destination_XMLEncoding_w_Dll">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_ALPHA"/>
                <StoredAs val="2"/>
                <Size val="3"/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
          </Columns>
        </Resource>
        <Information>
          <Key>
            <Column/>
            <Mode val="N"/>
          </Key>
          <DB/>
          <Sort>
            <CLS val="A"/>
          </Sort>
          <ForceRecordDelete DEL="N"/>
          <EndTaskCondition val="Y"/>
          <EvaluateEndCondition val="A"/>
          <InitialMode val="M"/>
          <Locate Direction="A"/>
          <Range Direction="A"/>
          <VarRange/>
          <TaskProperties>
            <SelectionTable val="N"/>
            <ConfirmUpdate CNFU="N"/>
            <ConfirmCancel val="N"/>
            <ErrorStrategy val="R"/>
            <LockingStrategy val="M"/>
            <CacheStrategy val="T"/>
            <ForceRecordSuffix val="N"/>
            <TransactionMode val="P"/>
            <TransactionBegin val="N"/>
            <PreloadView val="N"/>
            <KeepCreatedContext val="N"/>
          </TaskProperties>
          <SIDE_WIN>
            <AllowOptions val="N"/>
            <AllowQuery val="Y"/>
            <AllowModify val="Y"/>
            <AllowCreate val="Y"/>
            <AllowDelete val="Y"/>
            <AllowLocate val="Y"/>
            <AllowRange val="Y"/>
            <AllowIndexChange val="Y"/>
            <AllowSorting val="Y"/>
            <AllowIOFiles val="Y"/>
            <RecordCycle val="Y"/>
            <AllowEvents val="Y"/>
            <AllowIndexOptimization val="Y"/>
            <AllowLocationInQuery val="Y"/>
            <AllowPrintingData val="N"/>
          </SIDE_WIN>
          <WIN>
            <OpenTaskWindow val="N"/>
            <CloseTaskWindow val="Y"/>
            <ForegroundWindow val="Y"/>
            <FlipFld val="N"/>
            <RefreshTaskWindow ReturnValue="N"/>
          </WIN>
          <BOX>
            <Direction val="V"/>
          </BOX>
        </Information>
        <TaskLogic>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="M"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <_TotalVariabls val="4"/>
            <_TotalVirtuals val="4"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <DATAVIEW_SRC Type="M">
                  <Condition val="N"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </DATAVIEW_SRC>
              </LogicLine>
              <LogicLine>
                <Select Name="A">
                  <ASS/>
                  <Column val="1"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Select Name="B">
                  <ASS/>
                  <Column val="2"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="C">
                  <ASS/>
                  <Column val="3"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="D">
                  <ASS/>
                  <Column val="4"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="1"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="A"/>
                  <WithValue val="2"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="4"/>
                  <ReturnValue/>
                  <Condition Exp="3"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="5"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="1"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="6"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="8"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="9"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="10"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="11"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="12"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="13"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="14"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="7"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="15"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-2********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="A"/>
                  <WithValue val="16"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="18"/>
                  <ReturnValue/>
                  <Condition Exp="17"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="19"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="2"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="20"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="22"/>
                  <ReturnValue/>
                  <Condition Exp="21"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="23"/>
                  <ReturnValue/>
                  <Condition Exp="21"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="24"/>
                  <ReturnValue/>
                  <Condition Exp="21"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="25"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="26"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="27"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="28"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="21"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="29"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="30"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-2********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="32"/>
                  <ReturnValue/>
                  <Condition Exp="31"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
        </TaskLogic>
        <TaskForms>
          <FormEntry _last_test_id="1">
            <PropertyList model="FORM_GUI0">
              <Width/>
              <Height/>
              <_Comment/>
              <FormName valUnicode="Empty Program"/>
            </PropertyList>
          </FormEntry>
        </TaskForms>
        <Expressions>
          <Expression val="1">
            <ExpSyntax val="SetParam('xmlErr',' ')"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="2">
            <ExpSyntax val="GetParam ('000000000001000000000005F.GetItemAvailability_OUT')"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="3">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="4">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="5">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="6">
            <ExpSyntax val="BlobSize(A)&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="7">
            <ExpSyntax val="BlobSize(A)=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="8">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="9">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="10">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="11">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="12">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="13">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="14">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="15">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="16">
            <ExpSyntax val="GetParam ('000000000001000000000005F.GetItemAvailability_OUT')"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="17">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="18">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="19">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="20">
            <ExpSyntax val="BlobSize(A)&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="21">
            <ExpSyntax val="BlobSize(A)=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="22">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="23">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="24">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="25">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="26">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="27">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="28">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="29">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="30">
            <ExpSyntax val="SetParam ('000000000001000000000005F.GetItemAvailabilityResponse',B)"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="31">
            <ExpSyntax val="GetParam('xmlErr')&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="32">
            <ExpSyntax val="SetParam('C.sys.LastErrorInfo',GetParam('xmlErr'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
        </Expressions>
        <Task>
          <Header Description="Variable_2">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="736327" _time="67871" date="29//12//2016" time="18:51:11.1764825"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <IO Column="A">
              <Description val="xmlSource"/>
              <Format/>
              <Media val="V"/>
              <Access val="R"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
            <Columns>
              <Column id="1" name="D_2_F.AvailableQuantity">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
            </Columns>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y" Exp="20"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="1"/>
              <_TotalVirtuals val="1"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <Select Name="E">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Block SetParam RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="14"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="15"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Block SetParam RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="17"/>
                    <ReturnValue/>
                    <Condition Exp="16"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="18"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End SetParam XmlCnt RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Filter For Hole  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Filter For Hole  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="21"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=" **** Schema  Destination ****"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="E"/>
                    <WithValue val="22"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="23"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="1"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="2"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <RaiseEvent>
                    <Event>
                      <EventType val="P"/>
                      <Exp val="5"/>
                      <PublicObject/>
                    </Event>
                    <Wait val="89"/>
                    <Arguments>
                      <Argument>
                        <id val="0"/>
                        <Expression val="6"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="7"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Skip val="Y"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="8"/>
                        <Skip val="N"/>
                      </Argument>
                    </Arguments>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </RaiseEvent>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Temp SetParam TP   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="9"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="10"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="11"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Temp SetParam TP   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Temp SetParam TS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="12"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="13"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Temp SetParam TS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="XMLCnt(0,1,'/getItemAvailabilityResponse')=0"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="SetParam('Error',455)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source XML is not well-formed.'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="'SaveInternalMSG'"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="15"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="'txt'"/>
              <ExpAttribute val="T"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="SetParam('Temp_1_S_1_5_57_1_getItemAvailabilityResponse_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_5_57_1_getItemAvailabilityResponse'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="SetParam('Temp_XMLCnt_1_S_1_5_57_1_getItemAvailabilityResponse_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_5_57_1_getItemAvailabilityResponse'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="SetParam('S_1_5_57_1_getItemAvailabilityResponse',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="SetParam('S_1_5_57_1_getItemAvailabilityResponse',GetParam('Temp_1_S_1_5_57_1_getItemAvailabilityResponse_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="SetParam('XMLCnt_S_1_5_57_1_getItemAvailabilityResponse',GetParam('Temp_XMLCnt_1_S_1_5_57_1_getItemAvailabilityResponse_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="GetParam('S_1_5_57_1_getItemAvailabilityResponse')&gt;=GetParam('XMLCnt_S_1_5_57_1_getItemAvailabilityResponse')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="15">
              <ExpSyntax val="SetParam('S_1_5_57_1_getItemAvailabilityResponse',0)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="16">
              <ExpSyntax val="GetParam('S_1_5_57_1_getItemAvailabilityResponse') =0"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="17">
              <ExpSyntax val="SetParam('XMLCnt_S_1_5_57_1_getItemAvailabilityResponse',XMLCnt(0,1,'/getItemAvailabilityResponse'))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="18">
              <ExpSyntax val="SetParam('S_1_5_57_1_getItemAvailabilityResponse',GetParam('S_1_5_57_1_getItemAvailabilityResponse')+1)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="19">
              <ExpSyntax val="GetParam('S_1_5_57_1_getItemAvailabilityResponse')&gt;=GetParam('XMLCnt_S_1_5_57_1_getItemAvailabilityResponse')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="20">
              <ExpSyntax val="(ExpCalc('19'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="21">
              <ExpSyntax val="GetParam('XMLCnt_S_1_5_57_1_getItemAvailabilityResponse')&gt;0"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="22">
              <ExpSyntax val="Trim(Str(Val_e(xmlget(0,1,'/getItemAvailabilityResponse['&amp;trim(str(getparam('S_1_5_57_1_getItemAvailabilityResponse'),''))&amp;']'&amp;'/quantityAvailable','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')),'N10.2'),'N10.2'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="23">
              <ExpSyntax val="SetParam('000000000001000000000005F.AvailableQuantity',IF(rTrim( E )&lt;&gt;'',rTrim( E ),' '))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
        </Task>
        <Task>
          <Header Description="NoSource_HyrarchiDestination">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="736327" _time="67871" date="29//12//2016" time="18:51:11.1964841"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <IO Column="A">
              <Description val="xmlSource"/>
              <Format/>
              <Media val="V"/>
              <Access val="R"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Update>
                    <Variable val="C"/>
                    <WithValue val="9"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="10"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="11"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="12"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="13"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="14"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="15"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="16"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="17"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="D"/>
                    <WithValue val="18"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <CallTask>
                    <OperationType val="T"/>
                    <TaskID comp="-1" obj="1"/>
                    <Lock val="N"/>
                    <Arguments/>
                    <Wait val="Y"/>
                    <SyncData val="N"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </CallTask>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="19"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="20"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="B"/>
                    <WithValue val="21"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="22"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="1"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="2"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <RaiseEvent>
                    <Event>
                      <EventType val="P"/>
                      <Exp val="5"/>
                      <PublicObject/>
                    </Event>
                    <Wait val="89"/>
                    <Arguments>
                      <Argument>
                        <id val="0"/>
                        <Expression val="6"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="7"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Skip val="Y"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="8"/>
                        <Skip val="N"/>
                      </Argument>
                    </Arguments>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </RaiseEvent>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="XMLCnt(0,1,'/getItemAvailabilityResponse')=0"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="SetParam('Error',455)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source XML is not well-formed.'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="'SaveInternalMSG'"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="15"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="'txt'"/>
              <ExpAttribute val="T"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="UDF ('ibiowritter.openio',Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')),'wb', IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','16',IF(Trim(SharedValGet ('IBProjectEncoding'))='UTF-8','8','A')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="UDF ('ibiowritter.writeLnAsIs'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'&lt;?xml version=&quot;1.0&quot; encoding=&quot;'&amp;Trim(SharedValGet('IBProjectEncoding'))&amp;'&quot; standalone=&quot;no&quot; ?&gt;',C)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'sns0','http://oracle.e1.bssv.JP410000/',C)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'map','http://systinet.com/mapping/',C)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'xsd','http://www.w3.org/2001/XMLSchema',C)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'xs','http://www.w3.org/2001/XMLSchema',C)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="15">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'sns1','http://www.w3.org/2001/XMLSchema',C)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="16">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'ns1','http://www.w3.org/2001/XMLSchema',C)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="17">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'xsi','http://www.w3.org/2001/XMLSchema-instance',C)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="18">
              <ExpSyntax val="IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',IF(Trim(SharedValGet ('IBProjectEncoding'))='UTF-8','_8',''))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="19">
              <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'L','','','',C,0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="20">
              <ExpSyntax val="UDF ('ibiowritter.closeio',C)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="21">
              <ExpSyntax val="File2Blb(Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="22">
              <ExpSyntax val="FileDelete(Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
          <Task>
            <Header Description="sns0:getItemAvailabilityResponse">
              <Public/>
              <ExecutionRight/>
              <Resident val="N"/>
              <SQL val="N"/>
              <ReturnValue>
                <ReturnValueAttr/>
                <ParametersAttributes/>
              </ReturnValue>
              <SqlWhereExist val="N"/>
              <TaskType val="B"/>
              <External val="Y"/>
              <LastModified _date="736327" _time="67871" date="29//12//2016" time="18:51:11.1964841"/>
            </Header>
            <ReturnValueExpression/>
            <Resource>
              <Columns>
                <Column id="1" name="D_3_itemCatalog">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="2" name="D_3_itemCustomer">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="3" name="D_3_itemId">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_NUMERIC"/>
                    <StoredAs val="6"/>
                    <Size val="8"/>
                    <_Dec val="0"/>
                    <_Whole val="7"/>
                    <_Negative val="0"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="7"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="4" name="D_3_itemProduct">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="5" name="D_3_quantityAvailable">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_NUMERIC"/>
                    <StoredAs val="6"/>
                    <Size val="8"/>
                    <_Dec val="2"/>
                    <_Whole val="10"/>
                    <_Negative val="0"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="10.2"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="6" name="D_3_transactionUnitOfMeasure">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
              </Columns>
            </Resource>
            <Information>
              <Key>
                <Column/>
                <Mode val="N"/>
              </Key>
              <DB/>
              <Sort>
                <CLS val="A"/>
              </Sort>
              <ForceRecordDelete DEL="N"/>
              <EndTaskCondition val="Y" Exp="12"/>
              <EvaluateEndCondition val="A"/>
              <InitialMode val="M"/>
              <Locate Direction="A"/>
              <Range Direction="A"/>
              <VarRange/>
              <TaskProperties>
                <SelectionTable val="N"/>
                <ConfirmUpdate CNFU="N"/>
                <ConfirmCancel val="N"/>
                <ErrorStrategy val="R"/>
                <LockingStrategy val="M"/>
                <CacheStrategy val="T"/>
                <ForceRecordSuffix val="N"/>
                <TransactionMode val="P"/>
                <TransactionBegin val="N"/>
                <PreloadView val="N"/>
                <KeepCreatedContext val="N"/>
              </TaskProperties>
              <SIDE_WIN>
                <AllowOptions val="N"/>
                <AllowQuery val="Y"/>
                <AllowModify val="Y"/>
                <AllowCreate val="Y"/>
                <AllowDelete val="Y"/>
                <AllowLocate val="Y"/>
                <AllowRange val="Y"/>
                <AllowIndexChange val="Y"/>
                <AllowSorting val="Y"/>
                <AllowIOFiles val="Y"/>
                <RecordCycle val="Y"/>
                <AllowEvents val="Y"/>
                <AllowIndexOptimization val="Y"/>
                <AllowLocationInQuery val="Y"/>
                <AllowPrintingData val="N"/>
              </SIDE_WIN>
              <WIN>
                <OpenTaskWindow val="N"/>
                <CloseTaskWindow val="Y"/>
                <ForegroundWindow val="Y"/>
                <FlipFld val="N"/>
                <RefreshTaskWindow ReturnValue="N"/>
              </WIN>
              <BOX>
                <Direction val="V"/>
              </BOX>
            </Information>
            <TaskLogic>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="M"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <_TotalVariabls val="6"/>
                <_TotalVirtuals val="6"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <DATAVIEW_SRC Type="M">
                      <Condition val="N"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </DATAVIEW_SRC>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="E">
                      <ASS/>
                      <Column val="1"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="F">
                      <ASS/>
                      <Column val="2"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="G">
                      <ASS/>
                      <Column val="3"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="H">
                      <ASS/>
                      <Column val="4"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="I">
                      <ASS/>
                      <Column val="5"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="J">
                      <ASS/>
                      <Column val="6"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Source Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Block SetParam RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                      <Condition Exp="6"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </BLOCK>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="7"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <END_BLK/>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Block SetParam RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="9"/>
                      <ReturnValue/>
                      <Condition Exp="8"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="10"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End SetParam XmlCnt RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Filter For Hole  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Filter For Hole  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                      <Condition Exp="13"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </BLOCK>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Source Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=" **** Schema  Destination ****"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="14"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="E"/>
                      <WithValue val="15"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="16"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="F"/>
                      <WithValue val="17"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="18"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="G"/>
                      <WithValue val="19"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="20"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="H"/>
                      <WithValue val="21"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="22"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="I"/>
                      <WithValue val="23"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="24"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="J"/>
                      <WithValue val="25"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="26"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <END_BLK/>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Temp SetParam TP   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="1"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="2"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="3"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Temp SetParam TP   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Temp SetParam TS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="4"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="5"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Temp SetParam TS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
            </TaskLogic>
            <TaskForms>
              <FormEntry _last_test_id="1">
                <PropertyList model="FORM_GUI0">
                  <Width/>
                  <Height/>
                  <_Comment/>
                  <FormName valUnicode="Empty Program"/>
                </PropertyList>
              </FormEntry>
            </TaskForms>
            <Expressions>
              <Expression val="1">
                <ExpSyntax val="SetParam('Temp_2_S_1_5_57_1_getItemAvailabilityResponse_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_5_57_1_getItemAvailabilityResponse'))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="2">
                <ExpSyntax val="SetParam('Temp_XMLCnt_2_S_1_5_57_1_getItemAvailabilityResponse_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_5_57_1_getItemAvailabilityResponse'))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="3">
                <ExpSyntax val="SetParam('S_1_5_57_1_getItemAvailabilityResponse',0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="4">
                <ExpSyntax val="SetParam('S_1_5_57_1_getItemAvailabilityResponse',GetParam('Temp_2_S_1_5_57_1_getItemAvailabilityResponse_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="5">
                <ExpSyntax val="SetParam('XMLCnt_S_1_5_57_1_getItemAvailabilityResponse',GetParam('Temp_XMLCnt_2_S_1_5_57_1_getItemAvailabilityResponse_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="6">
                <ExpSyntax val="GetParam('S_1_5_57_1_getItemAvailabilityResponse')&gt;=GetParam('XMLCnt_S_1_5_57_1_getItemAvailabilityResponse')"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="7">
                <ExpSyntax val="SetParam('S_1_5_57_1_getItemAvailabilityResponse',0)"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="8">
                <ExpSyntax val="GetParam('S_1_5_57_1_getItemAvailabilityResponse') =0"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="9">
                <ExpSyntax val="SetParam('XMLCnt_S_1_5_57_1_getItemAvailabilityResponse',XMLCnt(1,1,'/getItemAvailabilityResponse'))"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="10">
                <ExpSyntax val="SetParam('S_1_5_57_1_getItemAvailabilityResponse',GetParam('S_1_5_57_1_getItemAvailabilityResponse')+1)"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="11">
                <ExpSyntax val="GetParam('S_1_5_57_1_getItemAvailabilityResponse')&gt;=GetParam('XMLCnt_S_1_5_57_1_getItemAvailabilityResponse')"/>
                <ExpAttribute val="L"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="12">
                <ExpSyntax val="(ExpCalc('11'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
                <ExpAttribute val="L"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="13">
                <ExpSyntax val="GetParam('XMLCnt_S_1_5_57_1_getItemAvailabilityResponse')&gt;0"/>
                <ExpAttribute val="L"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="14">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'C','sns0:getItemAvailabilityResponse','sns0:getItemAvailabilityResponse','',C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="15">
                <ExpSyntax val="xmlget(1,1,'/getItemAvailabilityResponse['&amp;trim(str(getparam('S_1_5_57_1_getItemAvailabilityResponse'),''))&amp;']'&amp;'/item['&amp;'1'&amp;']'&amp;'/itemCatalog','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="16">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','itemCatalog','sns0:getItemAvailabilityResponse/item/itemCatalog',rtrim(E),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="17">
                <ExpSyntax val="xmlget(1,1,'/getItemAvailabilityResponse['&amp;trim(str(getparam('S_1_5_57_1_getItemAvailabilityResponse'),''))&amp;']'&amp;'/item['&amp;'1'&amp;']'&amp;'/itemCustomer','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="18">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','itemCustomer','sns0:getItemAvailabilityResponse/item/itemCustomer',rtrim(F),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="19">
                <ExpSyntax val="Val(xmlget(1,1,'/getItemAvailabilityResponse['&amp;trim(str(getparam('S_1_5_57_1_getItemAvailabilityResponse'),''))&amp;']'&amp;'/item['&amp;'1'&amp;']'&amp;'/itemId','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')),'N7')"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="20">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','itemId','sns0:getItemAvailabilityResponse/item/itemId',trim(str(G,'N7')),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="21">
                <ExpSyntax val="xmlget(1,1,'/getItemAvailabilityResponse['&amp;trim(str(getparam('S_1_5_57_1_getItemAvailabilityResponse'),''))&amp;']'&amp;'/item['&amp;'1'&amp;']'&amp;'/itemProduct','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="22">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','itemProduct','sns0:getItemAvailabilityResponse/item/itemProduct',rtrim(H),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="23">
                <ExpSyntax val="Val_e(xmlget(1,1,'/getItemAvailabilityResponse['&amp;trim(str(getparam('S_1_5_57_1_getItemAvailabilityResponse'),''))&amp;']'&amp;'/quantityAvailable','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')),'N10.2')"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="24">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','quantityAvailable','sns0:getItemAvailabilityResponse/quantityAvailable',trim(str(I,'N10.2')),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="25">
                <ExpSyntax val="xmlget(1,1,'/getItemAvailabilityResponse['&amp;trim(str(getparam('S_1_5_57_1_getItemAvailabilityResponse'),''))&amp;']'&amp;'/transactionUnitOfMeasure','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="26">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','transactionUnitOfMeasure','sns0:getItemAvailabilityResponse/transactionUnitOfMeasure',rtrim(J),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
            </Expressions>
          </Task>
        </Task>
      </Task>
      <SubTaskNumber/>
    </Programs>
  </ProgramsRepository>
</Application>
