<?xml version="1.0" encoding="utf-8"?>
<Application>
  <ModelsRepository>
    <Models/>
  </ModelsRepository>
  <DataSourceRepository/>
  <Header>
    <Version val="12050"/>
    <APPLICATION val="Y"/>
    <WithIsn val="N"/>
    <Exe/>
    <_InternalTask/>
    <IsRoot/>
    <InIndex/>
    <WITH_MODELS/>
    <MAIN_PRG_VARS val="0"/>
    <MAIN_PRG_DSPS val="1"/>
    <Arguments END="2" START="2"/>
  </Header>
  <ProgramsRepository>
    <Programs>
      <Task>
        <Header Description="map_2_3_24">
          <Public val="map_2_3_24"/>
          <ExecutionRight/>
          <Resident val="N"/>
          <SQL val="N"/>
          <ReturnValue>
            <ReturnValueAttr/>
            <ParametersAttributes/>
          </ReturnValue>
          <SqlWhereExist val="N"/>
          <TaskType val="B"/>
          <External val="Y"/>
          <LastModified _date="736327" _time="49163" date="29//12//2016" time="13:39:23.0513080"/>
        </Header>
        <ReturnValueExpression/>
        <Resource>
          <Columns>
            <Column id="1" name="6_Source_DataBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="2" name="5_Destination_DataBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="29"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="3" name="5_Destination_XMLIoPtrDll">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_NUMERIC"/>
                <StoredAs/>
                <Size/>
                <_Dec/>
                <_Whole val="3"/>
                <_Negative/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
            <Column id="4" name="5_Destination_XMLEncoding_w_Dll">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_ALPHA"/>
                <StoredAs val="2"/>
                <Size val="3"/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
          </Columns>
        </Resource>
        <Information>
          <Key>
            <Column/>
            <Mode val="N"/>
          </Key>
          <DB/>
          <Sort>
            <CLS val="A"/>
          </Sort>
          <ForceRecordDelete DEL="N"/>
          <EndTaskCondition val="Y"/>
          <EvaluateEndCondition val="A"/>
          <InitialMode val="M"/>
          <Locate Direction="A"/>
          <Range Direction="A"/>
          <VarRange/>
          <TaskProperties>
            <SelectionTable val="N"/>
            <ConfirmUpdate CNFU="N"/>
            <ConfirmCancel val="N"/>
            <ErrorStrategy val="R"/>
            <LockingStrategy val="M"/>
            <CacheStrategy val="T"/>
            <ForceRecordSuffix val="N"/>
            <TransactionMode val="P"/>
            <TransactionBegin val="N"/>
            <PreloadView val="N"/>
            <KeepCreatedContext val="N"/>
          </TaskProperties>
          <SIDE_WIN>
            <AllowOptions val="N"/>
            <AllowQuery val="Y"/>
            <AllowModify val="Y"/>
            <AllowCreate val="Y"/>
            <AllowDelete val="Y"/>
            <AllowLocate val="Y"/>
            <AllowRange val="Y"/>
            <AllowIndexChange val="Y"/>
            <AllowSorting val="Y"/>
            <AllowIOFiles val="Y"/>
            <RecordCycle val="Y"/>
            <AllowEvents val="Y"/>
            <AllowIndexOptimization val="Y"/>
            <AllowLocationInQuery val="Y"/>
            <AllowPrintingData val="N"/>
          </SIDE_WIN>
          <WIN>
            <OpenTaskWindow val="N"/>
            <CloseTaskWindow val="Y"/>
            <ForegroundWindow val="Y"/>
            <FlipFld val="N"/>
            <RefreshTaskWindow ReturnValue="N"/>
          </WIN>
          <BOX>
            <Direction val="V"/>
          </BOX>
        </Information>
        <TaskLogic>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="M"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <_TotalVariabls val="4"/>
            <_TotalVirtuals val="4"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <DATAVIEW_SRC Type="M">
                  <Condition val="N"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </DATAVIEW_SRC>
              </LogicLine>
              <LogicLine>
                <Select Name="A">
                  <ASS/>
                  <Column val="1"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Select Name="B">
                  <ASS/>
                  <Column val="2"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="C">
                  <ASS/>
                  <Column val="3"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Select Name="D">
                  <ASS/>
                  <Column val="4"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="1"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="A"/>
                  <WithValue val="2"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="4"/>
                  <ReturnValue/>
                  <Condition Exp="3"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="5"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="1"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="6"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="8"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="9"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="10"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="11"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="12"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="13"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="14"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="7"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="15"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-2********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="A"/>
                  <WithValue val="16"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="18"/>
                  <ReturnValue/>
                  <Condition Exp="17"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="19"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="2"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="20"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="22"/>
                  <ReturnValue/>
                  <Condition Exp="21"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="23"/>
                  <ReturnValue/>
                  <Condition Exp="21"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="24"/>
                  <ReturnValue/>
                  <Condition Exp="21"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="25"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="26"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="27"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="28"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="21"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="29"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Update>
                  <Variable val="B"/>
                  <WithValue val="30"/>
                  <Incremental val="N"/>
                  <ForcedUpdate val="Y"/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Update>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="31"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-2********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="33"/>
                  <ReturnValue/>
                  <Condition Exp="32"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
        </TaskLogic>
        <TaskForms>
          <FormEntry _last_test_id="1">
            <PropertyList model="FORM_GUI0">
              <Width/>
              <Height/>
              <_Comment/>
              <FormName valUnicode="Empty Program"/>
            </PropertyList>
          </FormEntry>
        </TaskForms>
        <Expressions>
          <Expression val="1">
            <ExpSyntax val="SetParam('xmlErr',' ')"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="2">
            <ExpSyntax val="GetParam ('C.magTriggerData')"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="3">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="4">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="5">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="6">
            <ExpSyntax val="BlobSize(A)&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="7">
            <ExpSyntax val="BlobSize(A)=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="8">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="9">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="10">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="11">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="12">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="13">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="14">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="15">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="16">
            <ExpSyntax val="GetParam ('C.magTriggerData')"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="17">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="18">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="19">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="20">
            <ExpSyntax val="BlobSize(A)&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="21">
            <ExpSyntax val="BlobSize(A)=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="22">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="23">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="24">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="25">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="26">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="27">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="28">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="29">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="30">
            <ExpSyntax val="BlobAddBom(B,1)"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="31">
            <ExpSyntax val="SetParam ('C.magTriggerData',B)"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="32">
            <ExpSyntax val="GetParam('xmlErr')&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="33">
            <ExpSyntax val="SetParam('C.sys.LastErrorInfo',GetParam('xmlErr'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
        </Expressions>
        <Task>
          <Header Description="D1">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="736327" _time="49163" date="29//12//2016" time="13:39:23.0513080"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <IO Column="A">
              <Description val="xmlSource"/>
              <Format/>
              <Media val="V"/>
              <Access val="R"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
            <Columns>
              <Column id="1" name="D_4_C.magBillingId">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="2" name="D_4_C.magOrderId">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
              <Column id="3" name="D_4_C.magPurchaseOrderId">
                <PropertyList model="FIELD">
                  <Model attr_obj="FIELD_UNICODE"/>
                  <NullAllowed val="Y"/>
                  <StoredAs val="32"/>
                  <Size val="60"/>
                  <_FieldStyle val="1"/>
                  <Picture valUnicode="30"/>
                  <Definition val="2"/>
                </PropertyList>
              </Column>
            </Columns>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y" Exp="20"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <_TotalVariabls val="3"/>
              <_TotalVirtuals val="3"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
                <LogicLine>
                  <Select Name="E">
                    <ASS/>
                    <Column val="1"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="F">
                    <ASS/>
                    <Column val="2"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
                <LogicLine>
                  <Select Name="G">
                    <ASS/>
                    <Column val="3"/>
                    <Type val="V"/>
                    <IsParameter val="N"/>
                    <_RecomputeIndex val="1"/>
                    <_FormIndex val="1"/>
                    <_ControlIndex val="1"/>
                    <_OleSubformIdx val="1"/>
                    <_TabbingOrderDspIndex val="1"/>
                    <DIFF_UPDATE val="T"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </Select>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Block SetParam RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="14"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="15"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Block SetParam RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="17"/>
                    <ReturnValue/>
                    <Condition Exp="16"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="18"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End SetParam XmlCnt RS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Filter For Hole  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Filter For Hole  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="21"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Source Builder   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=" **** Schema  Destination ****"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***Begin Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="E"/>
                    <WithValue val="22"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="23"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="F"/>
                    <WithValue val="24"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="25"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="G"/>
                    <WithValue val="26"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="27"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="   ***End Update Destination Vars   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="1"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="2"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <RaiseEvent>
                    <Event>
                      <EventType val="P"/>
                      <Exp val="5"/>
                      <PublicObject/>
                    </Event>
                    <Wait val="89"/>
                    <Arguments>
                      <Argument>
                        <id val="0"/>
                        <Expression val="6"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="7"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Skip val="Y"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="8"/>
                        <Skip val="N"/>
                      </Argument>
                    </Arguments>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </RaiseEvent>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Temp SetParam TP   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="9"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="10"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="11"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Temp SetParam TP   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin Temp SetParam TS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="12"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="13"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End Temp SetParam TS   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="XMLCnt(0,1,'/magentoCreateOrder')=0"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="SetParam('Error',455)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source XML is not well-formed.'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="'SaveInternalMSG'"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="15"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="'txt'"/>
              <ExpAttribute val="T"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="SetParam('Temp_1_S_2_3_24_6_magentoCreateOrder_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_3_24_6_magentoCreateOrder'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="SetParam('Temp_XMLCnt_1_S_2_3_24_6_magentoCreateOrder_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder'))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="SetParam('S_2_3_24_6_magentoCreateOrder',0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="SetParam('S_2_3_24_6_magentoCreateOrder',GetParam('Temp_1_S_2_3_24_6_magentoCreateOrder_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="SetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder',GetParam('Temp_XMLCnt_1_S_2_3_24_6_magentoCreateOrder_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="GetParam('S_2_3_24_6_magentoCreateOrder')&gt;=GetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="15">
              <ExpSyntax val="SetParam('S_2_3_24_6_magentoCreateOrder',0)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="16">
              <ExpSyntax val="GetParam('S_2_3_24_6_magentoCreateOrder') =0"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="17">
              <ExpSyntax val="SetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder',XMLCnt(0,1,'/magentoCreateOrder'))"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="18">
              <ExpSyntax val="SetParam('S_2_3_24_6_magentoCreateOrder',GetParam('S_2_3_24_6_magentoCreateOrder')+1)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="19">
              <ExpSyntax val="GetParam('S_2_3_24_6_magentoCreateOrder')&gt;=GetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder')"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="20">
              <ExpSyntax val="(ExpCalc('19'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="21">
              <ExpSyntax val="GetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder')&gt;0"/>
              <ExpAttribute val="L"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="22">
              <ExpSyntax val="xmlget(0,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/billingId','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="23">
              <ExpSyntax val="SetParam('C.magBillingId',IF(rTrim( E )&lt;&gt;'',rTrim( E ),' '))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="24">
              <ExpSyntax val="xmlget(0,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/orderId','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="25">
              <ExpSyntax val="SetParam('C.magOrderId',IF(rTrim( F )&lt;&gt;'',rTrim( F ),' '))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="26">
              <ExpSyntax val="xmlget(0,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/purchaseOrder','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="27">
              <ExpSyntax val="SetParam('C.magPurchaseOrderId',IF(rTrim( G )&lt;&gt;'',rTrim( G ),' '))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
        </Task>
        <Task>
          <Header Description="NoSource_HyrarchiDestination">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="736327" _time="49163" date="29//12//2016" time="13:39:23.0533058"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <IO Column="A">
              <Description val="xmlSource"/>
              <Format/>
              <Media val="V"/>
              <Access val="R"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Update>
                    <Variable val="C"/>
                    <WithValue val="9"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="10"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="11"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="D"/>
                    <WithValue val="12"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <CallTask>
                    <OperationType val="T"/>
                    <TaskID comp="-1" obj="1"/>
                    <Lock val="N"/>
                    <Arguments/>
                    <Wait val="Y"/>
                    <SyncData val="N"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </CallTask>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="13"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="14"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Update>
                    <Variable val="B"/>
                    <WithValue val="15"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="16"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="1"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="2"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <RaiseEvent>
                    <Event>
                      <EventType val="P"/>
                      <Exp val="5"/>
                      <PublicObject/>
                    </Event>
                    <Wait val="89"/>
                    <Arguments>
                      <Argument>
                        <id val="0"/>
                        <Expression val="6"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="7"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Skip val="Y"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="8"/>
                        <Skip val="N"/>
                      </Argument>
                    </Arguments>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </RaiseEvent>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="XMLCnt(0,1,'/magentoCreateOrder')=0"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="SetParam('Error',455)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source XML is not well-formed.'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="'SaveInternalMSG'"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="15"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="'txt'"/>
              <ExpAttribute val="T"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="UDF ('ibiowritter.openio',Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')),'wb', IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','16',IF(Trim(SharedValGet ('IBProjectEncoding'))='UTF-8','8','A')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="UDF ('ibiowritter.writeLnAsIs'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'&lt;?xml version=&quot;1.0&quot; encoding=&quot;'&amp;Trim(SharedValGet('IBProjectEncoding'))&amp;'&quot; standalone=&quot;no&quot; ?&gt;',C)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="UDF ('ibiowritter.insertNS'&amp;IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',''),'xsi','http://www.w3.org/2001/XMLSchema-instance',C)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="IF(Trim(SharedValGet('IBProjectEncoding'))='UTF-16','_w',IF(Trim(SharedValGet ('IBProjectEncoding'))='UTF-8','_8',''))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'L','','','',C,0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="UDF ('ibiowritter.closeio',C)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="15">
              <ExpSyntax val="File2Blb(Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="16">
              <ExpSyntax val="FileDelete(Trim(VarCurrN('UNIQ_FILE_NAME_NOT_DOM')))"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
          <Task>
            <Header Description="magentoCreateOrder">
              <Public/>
              <ExecutionRight/>
              <Resident val="N"/>
              <SQL val="N"/>
              <ReturnValue>
                <ReturnValueAttr/>
                <ParametersAttributes/>
              </ReturnValue>
              <SqlWhereExist val="N"/>
              <TaskType val="B"/>
              <External val="Y"/>
              <LastModified _date="736327" _time="49163" date="29//12//2016" time="13:39:23.0533058"/>
            </Header>
            <ReturnValueExpression/>
            <Resource>
              <Columns>
                <Column id="1" name="D_5_orderId">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="2" name="D_5_createdAt">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_DATE"/>
                    <StoredAs val="19"/>
                    <Size val="8"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="YYYY-MM-DD"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="3" name="D_5_updatedAt">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_DATE"/>
                    <StoredAs val="19"/>
                    <Size val="8"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="YYYY-MM-DD"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="4" name="D_5_shippingAmount">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_NUMERIC"/>
                    <StoredAs val="6"/>
                    <Size val="8"/>
                    <_Dec val="2"/>
                    <_Whole val="10"/>
                    <_Negative val="0"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="10.2"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="5" name="D_5_taxAmount">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_NUMERIC"/>
                    <StoredAs val="6"/>
                    <Size val="8"/>
                    <_Dec val="2"/>
                    <_Whole val="10"/>
                    <_Negative val="0"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="10.2"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="6" name="D_5_shippingId">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="7" name="D_5_shippingTo">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="8" name="D_5_billingId">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="9" name="D_5_billingTo">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="10" name="D_5_discountAmount">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_NUMERIC"/>
                    <StoredAs val="6"/>
                    <Size val="8"/>
                    <_Dec val="2"/>
                    <_Whole val="10"/>
                    <_Negative val="0"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="10.2"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="11" name="D_5_subTotal">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_NUMERIC"/>
                    <StoredAs val="6"/>
                    <Size val="8"/>
                    <_Dec val="2"/>
                    <_Whole val="10"/>
                    <_Negative val="0"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="10.2"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="12" name="D_5_grandTotal">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_NUMERIC"/>
                    <StoredAs val="6"/>
                    <Size val="8"/>
                    <_Dec val="2"/>
                    <_Whole val="10"/>
                    <_Negative val="0"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="10.2"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="13" name="D_5_status">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="14" name="D_5_state">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="15" name="D_5_orderCurrencyCode">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="16" name="D_5_customerEmail">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
                <Column id="17" name="D_5_purchaseOrder">
                  <PropertyList model="FIELD">
                    <Model attr_obj="FIELD_UNICODE"/>
                    <StoredAs val="32"/>
                    <Size val="2000"/>
                    <_FieldStyle val="1"/>
                    <Picture valUnicode="1000"/>
                    <Definition val="2"/>
                  </PropertyList>
                </Column>
              </Columns>
            </Resource>
            <Information>
              <Key>
                <Column/>
                <Mode val="N"/>
              </Key>
              <DB/>
              <Sort>
                <CLS val="A"/>
              </Sort>
              <ForceRecordDelete DEL="N"/>
              <EndTaskCondition val="Y" Exp="12"/>
              <EvaluateEndCondition val="A"/>
              <InitialMode val="M"/>
              <Locate Direction="A"/>
              <Range Direction="A"/>
              <VarRange/>
              <TaskProperties>
                <SelectionTable val="N"/>
                <ConfirmUpdate CNFU="N"/>
                <ConfirmCancel val="N"/>
                <ErrorStrategy val="R"/>
                <LockingStrategy val="M"/>
                <CacheStrategy val="T"/>
                <ForceRecordSuffix val="N"/>
                <TransactionMode val="P"/>
                <TransactionBegin val="N"/>
                <PreloadView val="N"/>
                <KeepCreatedContext val="N"/>
              </TaskProperties>
              <SIDE_WIN>
                <AllowOptions val="N"/>
                <AllowQuery val="Y"/>
                <AllowModify val="Y"/>
                <AllowCreate val="Y"/>
                <AllowDelete val="Y"/>
                <AllowLocate val="Y"/>
                <AllowRange val="Y"/>
                <AllowIndexChange val="Y"/>
                <AllowSorting val="Y"/>
                <AllowIOFiles val="Y"/>
                <RecordCycle val="Y"/>
                <AllowEvents val="Y"/>
                <AllowIndexOptimization val="Y"/>
                <AllowLocationInQuery val="Y"/>
                <AllowPrintingData val="N"/>
              </SIDE_WIN>
              <WIN>
                <OpenTaskWindow val="N"/>
                <CloseTaskWindow val="Y"/>
                <ForegroundWindow val="Y"/>
                <FlipFld val="N"/>
                <RefreshTaskWindow ReturnValue="N"/>
              </WIN>
              <BOX>
                <Direction val="V"/>
              </BOX>
            </Information>
            <TaskLogic>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="M"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <_TotalVariabls val="17"/>
                <_TotalVirtuals val="17"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <DATAVIEW_SRC Type="M">
                      <Condition val="N"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </DATAVIEW_SRC>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="E">
                      <ASS/>
                      <Column val="1"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="F">
                      <ASS/>
                      <Column val="2"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="G">
                      <ASS/>
                      <Column val="3"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="H">
                      <ASS/>
                      <Column val="4"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="I">
                      <ASS/>
                      <Column val="5"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="J">
                      <ASS/>
                      <Column val="6"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="K">
                      <ASS/>
                      <Column val="7"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="L">
                      <ASS/>
                      <Column val="8"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="M">
                      <ASS/>
                      <Column val="9"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="N">
                      <ASS/>
                      <Column val="10"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="O">
                      <ASS/>
                      <Column val="11"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="P">
                      <ASS/>
                      <Column val="12"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="Q">
                      <ASS/>
                      <Column val="13"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="R">
                      <ASS/>
                      <Column val="14"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="S">
                      <ASS/>
                      <Column val="15"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="T">
                      <ASS/>
                      <Column val="16"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                  <LogicLine>
                    <Select Name="U">
                      <ASS/>
                      <Column val="17"/>
                      <Type val="V"/>
                      <IsParameter val="N"/>
                      <_RecomputeIndex val="1"/>
                      <_FormIndex val="1"/>
                      <_ControlIndex val="1"/>
                      <_OleSubformIdx val="1"/>
                      <_TabbingOrderDspIndex val="1"/>
                      <DIFF_UPDATE val="T"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </Select>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Source Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Block SetParam RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                      <Condition Exp="6"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </BLOCK>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="7"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <END_BLK/>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Block SetParam RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="9"/>
                      <ReturnValue/>
                      <Condition Exp="8"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="10"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End SetParam XmlCnt RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Filter For Hole  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Filter For Hole  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                      <Condition Exp="13"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </BLOCK>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Source Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=" **** Schema  Destination ****"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="14"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="E"/>
                      <WithValue val="15"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="16"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="F"/>
                      <WithValue val="17"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="18"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="G"/>
                      <WithValue val="19"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="20"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="H"/>
                      <WithValue val="21"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="22"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="I"/>
                      <WithValue val="23"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="24"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="J"/>
                      <WithValue val="25"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="26"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="K"/>
                      <WithValue val="27"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="28"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="L"/>
                      <WithValue val="29"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="30"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="M"/>
                      <WithValue val="31"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="32"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="N"/>
                      <WithValue val="33"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="34"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="O"/>
                      <WithValue val="35"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="36"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="P"/>
                      <WithValue val="37"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="38"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="Q"/>
                      <WithValue val="39"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="40"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="R"/>
                      <WithValue val="41"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="42"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="S"/>
                      <WithValue val="43"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="44"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="T"/>
                      <WithValue val="45"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="46"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Update>
                      <Variable val="U"/>
                      <WithValue val="47"/>
                      <Incremental val="N"/>
                      <ForcedUpdate val="Y"/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Update>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="48"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <CallTask>
                      <OperationType val="T"/>
                      <TaskID comp="-1" obj="1"/>
                      <Lock val="N"/>
                      <Arguments/>
                      <Wait val="Y"/>
                      <SyncData val="N"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </CallTask>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <END_BLK/>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Temp SetParam TP   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="1"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="2"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="3"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Temp SetParam TP   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Temp SetParam TS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="4"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="5"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Temp SetParam TS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
            </TaskLogic>
            <TaskForms>
              <FormEntry _last_test_id="1">
                <PropertyList model="FORM_GUI0">
                  <Width/>
                  <Height/>
                  <_Comment/>
                  <FormName valUnicode="Empty Program"/>
                </PropertyList>
              </FormEntry>
            </TaskForms>
            <Expressions>
              <Expression val="1">
                <ExpSyntax val="SetParam('Temp_2_S_2_3_24_6_magentoCreateOrder_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_3_24_6_magentoCreateOrder'))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="2">
                <ExpSyntax val="SetParam('Temp_XMLCnt_2_S_2_3_24_6_magentoCreateOrder_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder'))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="3">
                <ExpSyntax val="SetParam('S_2_3_24_6_magentoCreateOrder',0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="4">
                <ExpSyntax val="SetParam('S_2_3_24_6_magentoCreateOrder',GetParam('Temp_2_S_2_3_24_6_magentoCreateOrder_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="5">
                <ExpSyntax val="SetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder',GetParam('Temp_XMLCnt_2_S_2_3_24_6_magentoCreateOrder_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="6">
                <ExpSyntax val="GetParam('S_2_3_24_6_magentoCreateOrder')&gt;=GetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder')"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="7">
                <ExpSyntax val="SetParam('S_2_3_24_6_magentoCreateOrder',0)"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="8">
                <ExpSyntax val="GetParam('S_2_3_24_6_magentoCreateOrder') =0"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="9">
                <ExpSyntax val="SetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder',XMLCnt(1,1,'/magentoCreateOrder'))"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="10">
                <ExpSyntax val="SetParam('S_2_3_24_6_magentoCreateOrder',GetParam('S_2_3_24_6_magentoCreateOrder')+1)"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="11">
                <ExpSyntax val="GetParam('S_2_3_24_6_magentoCreateOrder')&gt;=GetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder')"/>
                <ExpAttribute val="L"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="12">
                <ExpSyntax val="(ExpCalc('11'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
                <ExpAttribute val="L"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="13">
                <ExpSyntax val="GetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder')&gt;0"/>
                <ExpAttribute val="L"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="14">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'C','magentoCreateOrder','magentoCreateOrder','',C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="15">
                <ExpSyntax val="xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/orderId','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="16">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','orderId','magentoCreateOrder/orderId',rtrim(E),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="17">
                <ExpSyntax val="dval(Trim(xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/createdAt','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))),'YYYY-MM-DD')"/>
                <ExpAttribute val="D"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="18">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','createdAt','magentoCreateOrder/createdAt',Dstr(F,'YYYY-MM-DD'),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="19">
                <ExpSyntax val="dval(Trim(xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/updatedAt','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))),'YYYY-MM-DD')"/>
                <ExpAttribute val="D"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="20">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','updatedAt','magentoCreateOrder/updatedAt',Dstr(G,'YYYY-MM-DD'),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="21">
                <ExpSyntax val="Val_e(xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/shippingAmount','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')),'N10.2')"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="22">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','shippingAmount','magentoCreateOrder/shippingAmount',trim(str(H,'N10.2')),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="23">
                <ExpSyntax val="Val_e(xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/taxAmount','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')),'N10.2')"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="24">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','taxAmount','magentoCreateOrder/taxAmount',trim(str(I,'N10.2')),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="25">
                <ExpSyntax val="xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/shippingId','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="26">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','shippingId','magentoCreateOrder/shippingId',rtrim(J),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="27">
                <ExpSyntax val="xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/shippingTo','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="28">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','shippingTo','magentoCreateOrder/shippingTo',rtrim(K),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="29">
                <ExpSyntax val="xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/billingId','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="30">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','billingId','magentoCreateOrder/billingId',rtrim(L),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="31">
                <ExpSyntax val="xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/billingTo','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="32">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','billingTo','magentoCreateOrder/billingTo',rtrim(M),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="33">
                <ExpSyntax val="Val_e(xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/discountAmount','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')),'N10.2')"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="34">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','discountAmount','magentoCreateOrder/discountAmount',trim(str(N,'N10.2')),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="35">
                <ExpSyntax val="Val_e(xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/subTotal','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')),'N10.2')"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="36">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','subTotal','magentoCreateOrder/subTotal',trim(str(O,'N10.2')),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="37">
                <ExpSyntax val="Val_e(xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/grandTotal','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')),'N10.2')"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="38">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','grandTotal','magentoCreateOrder/grandTotal',trim(str(P,'N10.2')),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="39">
                <ExpSyntax val="xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/status','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="40">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','status','magentoCreateOrder/status',rtrim(Q),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="41">
                <ExpSyntax val="xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/state','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="42">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','state','magentoCreateOrder/state',rtrim(R),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="43">
                <ExpSyntax val="xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/orderCurrencyCode','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="44">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','orderCurrencyCode','magentoCreateOrder/orderCurrencyCode',rtrim(S),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="45">
                <ExpSyntax val="xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/customerEmail','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="46">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','customerEmail','magentoCreateOrder/customerEmail',rtrim(T),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="47">
                <ExpSyntax val="xmlget(1,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/purchaseOrder','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="48">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','purchaseOrder','magentoCreateOrder/purchaseOrder',rtrim(U),C,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
            </Expressions>
            <Task>
              <Header Description="magentoCreateOrder/orderItems">
                <Public/>
                <ExecutionRight/>
                <Resident val="N"/>
                <SQL val="N"/>
                <ReturnValue>
                  <ReturnValueAttr/>
                  <ParametersAttributes/>
                </ReturnValue>
                <SqlWhereExist val="N"/>
                <TaskType val="B"/>
                <External val="Y"/>
                <LastModified _date="736327" _time="49163" date="29//12//2016" time="13:39:23.0623056"/>
              </Header>
              <ReturnValueExpression/>
              <Resource>
                <Columns>
                  <Column id="1" name="D_5_sku">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="2" name="D_5_qty">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_NUMERIC"/>
                      <StoredAs val="6"/>
                      <Size val="8"/>
                      <_Dec val="2"/>
                      <_Whole val="10"/>
                      <_Negative val="0"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="10.2"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="3" name="D_5_tax">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_NUMERIC"/>
                      <StoredAs val="6"/>
                      <Size val="8"/>
                      <_Dec val="2"/>
                      <_Whole val="10"/>
                      <_Negative val="0"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="10.2"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="4" name="D_5_price">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_NUMERIC"/>
                      <StoredAs val="6"/>
                      <Size val="8"/>
                      <_Dec val="2"/>
                      <_Whole val="10"/>
                      <_Negative val="0"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="10.2"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                </Columns>
              </Resource>
              <Information>
                <Key>
                  <Column/>
                  <Mode val="N"/>
                </Key>
                <DB/>
                <Sort>
                  <CLS val="A"/>
                </Sort>
                <ForceRecordDelete DEL="N"/>
                <EndTaskCondition val="Y" Exp="12"/>
                <EvaluateEndCondition val="A"/>
                <InitialMode val="M"/>
                <Locate Direction="A"/>
                <Range Direction="A"/>
                <VarRange/>
                <TaskProperties>
                  <SelectionTable val="N"/>
                  <ConfirmUpdate CNFU="N"/>
                  <ConfirmCancel val="N"/>
                  <ErrorStrategy val="R"/>
                  <LockingStrategy val="M"/>
                  <CacheStrategy val="T"/>
                  <ForceRecordSuffix val="N"/>
                  <TransactionMode val="P"/>
                  <TransactionBegin val="N"/>
                  <PreloadView val="N"/>
                  <KeepCreatedContext val="N"/>
                </TaskProperties>
                <SIDE_WIN>
                  <AllowOptions val="N"/>
                  <AllowQuery val="Y"/>
                  <AllowModify val="Y"/>
                  <AllowCreate val="Y"/>
                  <AllowDelete val="Y"/>
                  <AllowLocate val="Y"/>
                  <AllowRange val="Y"/>
                  <AllowIndexChange val="Y"/>
                  <AllowSorting val="Y"/>
                  <AllowIOFiles val="Y"/>
                  <RecordCycle val="Y"/>
                  <AllowEvents val="Y"/>
                  <AllowIndexOptimization val="Y"/>
                  <AllowLocationInQuery val="Y"/>
                  <AllowPrintingData val="N"/>
                </SIDE_WIN>
                <WIN>
                  <OpenTaskWindow val="N"/>
                  <CloseTaskWindow val="Y"/>
                  <ForegroundWindow val="Y"/>
                  <FlipFld val="N"/>
                  <RefreshTaskWindow ReturnValue="N"/>
                </WIN>
                <BOX>
                  <Direction val="V"/>
                </BOX>
              </Information>
              <TaskLogic>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="M"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <_TotalVariabls val="4"/>
                  <_TotalVirtuals val="4"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <DATAVIEW_SRC Type="M">
                        <Condition val="N"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </DATAVIEW_SRC>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="V">
                        <ASS/>
                        <Column val="1"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="W">
                        <ASS/>
                        <Column val="2"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="X">
                        <ASS/>
                        <Column val="3"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="Y">
                        <ASS/>
                        <Column val="4"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="S"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***Begin Source Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Block SetParam RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="6"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="7"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Block SetParam RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="9"/>
                        <ReturnValue/>
                        <Condition Exp="8"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="10"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End SetParam XmlCnt RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Filter For Hole  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Filter For Hole  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="13"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***End Source Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=" **** Schema  Destination ****"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="14"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***Begin Update Destination Vars   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="V"/>
                        <WithValue val="15"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="16"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="W"/>
                        <WithValue val="17"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="18"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="X"/>
                        <WithValue val="19"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="20"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="Y"/>
                        <WithValue val="21"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="22"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***End Update Destination Vars   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="P"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="T"/>
                  <Type val="P"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Temp SetParam TP   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="1"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="2"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="3"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Temp SetParam TP   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="T"/>
                  <Type val="S"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Temp SetParam TS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="4"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="5"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Temp SetParam TS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
              </TaskLogic>
              <TaskForms>
                <FormEntry _last_test_id="1">
                  <PropertyList model="FORM_GUI0">
                    <Width/>
                    <Height/>
                    <_Comment/>
                    <FormName valUnicode="Empty Program"/>
                  </PropertyList>
                </FormEntry>
              </TaskForms>
              <Expressions>
                <Expression val="1">
                  <ExpSyntax val="SetParam('Temp_3_S_2_3_24_6_magentoCreateOrder/orderItems_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_2_3_24_6_magentoCreateOrder/orderItems'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="2">
                  <ExpSyntax val="SetParam('Temp_XMLCnt_3_S_2_3_24_6_magentoCreateOrder/orderItems_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder/orderItems'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="3">
                  <ExpSyntax val="SetParam('S_2_3_24_6_magentoCreateOrder/orderItems',0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="4">
                  <ExpSyntax val="SetParam('S_2_3_24_6_magentoCreateOrder/orderItems',GetParam('Temp_3_S_2_3_24_6_magentoCreateOrder/orderItems_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="5">
                  <ExpSyntax val="SetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder/orderItems',GetParam('Temp_XMLCnt_3_S_2_3_24_6_magentoCreateOrder/orderItems_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="6">
                  <ExpSyntax val="GetParam('S_2_3_24_6_magentoCreateOrder/orderItems')&gt;=GetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder/orderItems')"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="7">
                  <ExpSyntax val="SetParam('S_2_3_24_6_magentoCreateOrder/orderItems',0)"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="8">
                  <ExpSyntax val="GetParam('S_2_3_24_6_magentoCreateOrder/orderItems') =0"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="9">
                  <ExpSyntax val="SetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder/orderItems',XMLCnt(2,1,'/magentoCreateOrder['&amp;Trim(Str(GetParam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']/orderItems'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="10">
                  <ExpSyntax val="SetParam('S_2_3_24_6_magentoCreateOrder/orderItems',GetParam('S_2_3_24_6_magentoCreateOrder/orderItems')+1)"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="11">
                  <ExpSyntax val="GetParam('S_2_3_24_6_magentoCreateOrder/orderItems')&gt;=GetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder/orderItems')"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="12">
                  <ExpSyntax val="(ExpCalc('11'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="13">
                  <ExpSyntax val="GetParam('XMLCnt_S_2_3_24_6_magentoCreateOrder/orderItems')&gt;0"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="14">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'C','orderItems','magentoCreateOrder/orderItems','',C,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="15">
                  <ExpSyntax val="xmlget(2,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/orderItems['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder/orderItems'),''))&amp;']'&amp;'/sku','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="16">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','sku','magentoCreateOrder/orderItems/sku',rtrim(V),C,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="17">
                  <ExpSyntax val="Val_e(xmlget(2,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/orderItems['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder/orderItems'),''))&amp;']'&amp;'/qty','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')),'N10.2')"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="18">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','qty','magentoCreateOrder/orderItems/qty',trim(str(W,'N10.2')),C,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="19">
                  <ExpSyntax val="Val_e(xmlget(2,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/orderItems['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder/orderItems'),''))&amp;']'&amp;'/tax','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')),'N10.2')"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="20">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','tax','magentoCreateOrder/orderItems/tax',trim(str(X,'N10.2')),C,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="21">
                  <ExpSyntax val="Val_e(xmlget(2,1,'/magentoCreateOrder['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder'),''))&amp;']'&amp;'/orderItems['&amp;trim(str(getparam('S_2_3_24_6_magentoCreateOrder/orderItems'),''))&amp;']'&amp;'/price','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')),'N10.2')"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="22">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart'&amp;trim(D),'S','price','magentoCreateOrder/orderItems/price',trim(str(Y,'N10.2')),C,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
              </Expressions>
            </Task>
          </Task>
        </Task>
      </Task>
      <SubTaskNumber/>
    </Programs>
  </ProgramsRepository>
</Application>
